### PR TITLE
complete header section with CSS and JS files

### LINKED ISSUE #6: Header Component

### PR DESCRIPTION
**Pull request by tosinibrahim96**
#6

### CODE REVIEW

**Review by bamiogunfemi — CHANGES_REQUESTED** [review]
The purple circle beside home should indicate that it's the active page, so please fix that

**Comment by tosinibrahim96** [comment]
> 
> 
> The purple circle beside home should indicate that it's the active page, so please fix that

Please can you show me an image so I can understand. When I view it here, it's active on the home tab

**Comment by bamiogunfemi** [comment]
> > The purple circle beside home should indicate that it's the active page, so please fix that
> 
> Please can you show me an image so I can understand. When I view it here, it's active on the home tab

image

**Review by bamiogunfemi — APPROVED** [review]
LGTM

**Review by iobami — COMMENTED** [review]
Beautiful work guys @tosinibrahim96 and @delecoder 

Might be nice if we can add some tiny things. I think our header need a higher z-index say z-index: 100, position: relative.

Then @media query 755 upwards, might be nice if nav-link width reduces so it's slightly far away from the logo

**Comment by tosinibrahim96** [comment]
> 
> 
> Beautiful work guys @tosinibrahim96 and @delecoder
> 
> Might be nice if we can add some tiny things. I think our header need a higher z-index say z-index: 100, position: relative.
> 
> Then @media query 755 upwards, might be nice if nav-link width reduces so it's slightly far away from the logo

Thanks boss

This is what 755px looks like. Please what do you mean when you say  
> nav-link width reduces so it's slightly far away from the logo

**Comment by iobami** [comment]
> Please what do you mean when you say
> 
> > nav-link width reduces so it's slightly far away from the logo

Okay, I'll edit and send a screenshot, you can also zoom in on the figma design.

Look at the space between BelleView and Home... Contact Us

We need to space the header that way

**Comment by iobami** [comment]
Suggestion, I think margin or padding space between home... Contact Us is too large.

**Comment by iobami** [comment]
hng-hotel-header1

**Comment by tosinibrahim96** [comment]
> 
> 
> hng-hotel-header1

This is the view on desktop screen and 755px is tablet. Are you saying this is how it should be viewed on tablet

**Comment by Xemicolon** [comment]
The space between the nav links, isn't it too much?

**Comment by Xemicolon** [comment]
The spacing between the nav links seems much..

**Review by iobami — APPROVED** [review]
Nice work. Well done my good sir

**Pull request merged**
