### PR TITLE
bug/ fixed gym image and text

### PR DESCRIPTION
**Pull request by LolaMedina**
## fixed image and text issue in gym section.
gym issue

### CODE REVIEW

**Comment by iobami** [comment]
Looks real good. Positioning on point. 

She said you should increase the font right? Add aboout 10 px to gym 

about 6px to text. See if it looks good

**Comment by iobami** [comment]
hotelissue16


What it looks like on my PC

**Comment by iobami** [comment]
Gym and text content need to move away from the image a little

**Comment by LolaMedina** [comment]
I made some changes
nes screen2
new screen

**Pull request merged**
