### PR TITLE
Footer patch

### LINKED ISSUE #5: Footer Component

### PR DESCRIPTION
**Pull request by jbrit**
I made necessary corrections, please review and merge.

### CODE REVIEW

**Review by devTam — COMMENTED** [review]
Looks good to me.

**Comment by Sproff** [comment]
Nice work

**Review by iobami — DISMISSED** [review]

**Review by iobami — COMMENTED** [review]
This is real good. I just need to confirm if we are meant to create separate files for our css.

**Review by bamiogunfemi — APPROVED** [review]
LGTM

**Pull request merged**
